
enum Queues {

  PY_FACTS = "PY_FACTS",
  PY_SW_SUGGESTION = "PY_SW_SUGGESTION",
  PY_EOX = "PY_EOX",
  PY_COVERAGE = "PY_COVERAGE",
  PY_INFORMATION = "PY_INFORMATION",
  PY_INVENTORY = "PY_INVENTORY",
  PY_BUGS = "PY_BUGS",
  PY_CONFIG = "PY_CONFIG",
  PY_VULNERABILITY = "PY_VULNERABILITY",

  PY_UPGRADE = "PY_UPGRADE",
  PY_CHECK_SW_UPGRADED = "PY_CHECK_SW_UPGRADED",

  JS_BUGS = "JS_BUGS",
  JS_CONFIG = "JS_CONFIG",
  JS_COVERAGE = "JS_COVERAGE",
  JS_EOX = "JS_EOX",
  JS_FACTS = "JS_FACTS",
  JS_INFORMATION = "JS_INFORMATION",
  JS_INVENTORY = "JS_INVENTORY",
  JS_SW_SUGGESTION = "JS_SW_SUGGESTION",
  JS_VULNERABILITY = "JS_VULNERABILITY",
  
  JS_DONE_CHECKER = "JS_DONE_CHECKER",
  JS_UPGRADE = "JS_UPGRADE",
  JS_CHECK_SW_UPGRADED = "JS_CHECK_SW_UPGRADED",
  
  JS_SAVE_TASK = "JS_SAVE_TASK"
}

export default Queues